const ElectionmapActionTypes = {
  FETCH_AVAILABLE_LAYERS: 'FETCH_AVAILABLE_LAYERS',
  FETCH_AVAILABLE_EXCEL_FILES: 'FETCH_AVAILABLE_EXCEL_FILES',
  FETCH_AVAILABLE_COLOR_FILES: 'FETCH_AVAILABLE_COLOR_FILES',
  POST_ELECTIONMAP: 'POST_ELECTIONMAP',
  POST_DISTRICT_LAYERS: 'POST_DISTRICT_LAYERS'
};

export default ElectionmapActionTypes;
