const ElectionmapActionTypes = {
	FETCH_AVAILABLE_LAYERS: 'FETCH_AVAILABLE_LAYERS',
	FETCH_AVAILABLE_EXCEL_FILES: 'FETCH_AVAILABLE_EXCEL_FILES',
	FETCH_AVAILABLE_COLOR_FILES: 'FETCH_AVAILABLE_COLOR_FILES',
	FETCH_AVAILABLE_CATEGORIES: 'FETCH_AVAILABLE_CATEGORIES',
	FETCH_MAP: 'FETCH_MAP',
	POST_ELECTIONMAP: 'POST_ELECTIONMAP',
	POST_DISTRICT_LAYERS: 'POST_DISTRICT_LAYERS',
	POST_COLOR_FILES: 'POST_COLOR_FILES',
	POST_XLSX: 'POST_XLSX',
	POST_CATEGORY: 'POST_CATEGORY',
	FETCH_CATEGORICAL_MAPLINKS: 'FETCH_CATEGORICAL_MAPLINKS',
};

export default ElectionmapActionTypes;
